package waffles.utils.alg.utilities.affine;

import waffles.utils.alg.lin.measure.matrix.Matrix;

/**
 * An {@code Affine} object can be transformed through a {@code LinearMap}.
 * This is done by passing its {@code Matrix} span to the map for multiplication.
 * In addition, the {@link #Factory()} method is used to generate a new affine
 * object given a matrix span generated by a {@code LinearMap}.
 *
 * @author Waffles
 * @since 18 Aug 2023
 * @version 1.0
 */
@FunctionalInterface
public interface Affine
{
	/**
	 * A {@code Factory} generates affine objects.
	 *
	 * @author Waffles
	 * @since Sep 10, 2019
	 * @version 1.0
	 * 
	 * 
	 * @see Affine
	 */
	@FunctionalInterface
	public static interface Factory
	{
		/**
		 * Creates a new {@code Affine} object.
		 * 
		 * @param m  a matrix span
		 * @return   an affine object
		 * 
		 * 
		 * @see Affine
		 * @see Matrix
		 */
		public abstract Affine create(Matrix m);
	}
	
	/**
	 * Returns an {@code Affine} object factory.
	 * 
	 * @return  an affine factory
	 * 
	 * 
	 * @see Factory
	 */
	public default Factory Factory()
	{
		return m -> m;
	}
	
	/**
	 * Returns an {@code Affine} matrix span.
	 * 
	 * @return  a matrix span
	 * 
	 * 
	 * @see Matrix
	 */
	public abstract Matrix Span();
}