package zeno.util.algebra.algorithms;

import zeno.util.algebra.linear.matrix.Matrix;
import zeno.util.tools.patterns.manipulators.Adaptable;

/**
 * The {@code Permutation} interface defines an algorithm that constructs a permutation matrix.
 *
 * @author Zeno
 * @since Apr 7, 2019
 * @version 1.0
 * 
 * 
 * @see Adaptable
 */
public interface Permutation extends Adaptable
{
	/**
	 * Returns the matrix generated by the {@code Permutation}.
	 * 
	 * @return  a permutation matrix
	 * 
	 * 
	 * @see Matrix
	 */
	public abstract Matrix P();
}