package waffles.utils.algebra.elements.linear;

import waffles.utils.algebra.elements.linear.matrix.Matrix;

/**
 * An {@code Affine} object is capable of being transformed through a {@code LinearMap2}.
 * This is accomplished by providing a {@code Matrix} span, which can be passed on to the
 * linear map for matrix multiplication. In addition, the implementation must provide
 * a {@link #Factory()} which constructs new {@code Affine} objects
 * given a matrix span generated by a {@code LinearMap2}.
 *
 * @author Waffles
 * @since 18 Aug 2023
 * @version 1.0
 */
public interface Affine
{
	/**
	 * The {@code Factory} interface defines a generator for {@code Affine} objects.
	 *
	 * @author Waffles
	 * @since Sep 10, 2019
	 * @version 1.0
	 * 
	 * 
	 * @see Affine
	 */
	@FunctionalInterface
	public static interface Factory
	{
		/**
		 * Creates a new {@code Affine} object from a {@code Matrix}.
		 * 
		 * @param m  a matrix span
		 * @return   a linearizable object
		 * 
		 * 
		 * @see Affine
		 * @see Matrix
		 */
		public abstract Affine create(Matrix m);
	}
	
	/**
	 * Returns a factory to generate {@code Affine} objects.
	 * 
	 * @return  an affine factory
	 * 
	 * 
	 * @see Factory
	 */
	public abstract Factory Factory();
	
	/**
	 * Returns the span of the {@code Affine} object.
	 * 
	 * @return  a matrix span
	 * 
	 * 
	 * @see Matrix
	 */
	public abstract Matrix Span();
}