package waffles.utils.algebra.elements.linear;

import waffles.utils.algebra.elements.linear.matrix.Matrix;

/**
 * A {@code Linearizable} object is capable of being transformed through a {@code LinearMap}.
 * This is accomplished by providing a {@code Matrix} span, which can be passed on to the
 * linear map for matrix multiplication. In addition, the implementation must provide
 * a {@link #Factory()} which constructs new {@code Linearizable} objects
 * given a matrix span generated by a {@code LinearMap}.
 *
 * @author Waffles
 * @since 18 Aug 2023
 * @version 1.0
 */
public interface Linearizable
{
	/**
	 * The {@code Factory} interface defines a generator for {@code Linearizable} objects.
	 *
	 * @author Waffles
	 * @since Sep 10, 2019
	 * @version 1.0
	 * 
	 * 
	 * @see Linearizable
	 */
	@FunctionalInterface
	public static interface Factory
	{
		/**
		 * Creates a new {@code Linearizable} object from a {@code Matrix}.
		 * 
		 * @param m  a matrix span
		 * @return   a linearizable object
		 * 
		 * 
		 * @see Linearizable
		 * @see Matrix
		 */
		public abstract Linearizable create(Matrix m);
	}
	
	/**
	 * Returns a factory to generate {@code Linearizable} objects.
	 * 
	 * @return  a linearizable factory
	 * 
	 * 
	 * @see Factory
	 */
	public abstract Factory Factory();
	
	/**
	 * Returns the span of the {@code Linearizable}.
	 * 
	 * @return  a matrix span
	 * 
	 * 
	 * @see Matrix
	 */
	public abstract Matrix Span();
}