package waffles.utils.algebra.elements.linear;

import waffles.utils.algebra.elements.linear.matrix.Matrix;

/**
 * A {@code Linearizable} object is capable of being transformed through a {@code LinearMap}.
 * This is accomplished by providing a {@code Matrix} span, which can be passed on to the
 * linear map for matrix multiplication. In addition, the implementation must provide
 * an {@link #instance(Matrix)} method which constructs new {@code Linearizable}
 * objects given a matrix span generated by a {@code LinearMap}.
 *
 * @author Waffles
 * @since 18 Aug 2023
 * @version 1.0
 */
public interface Linearizable
{
	/**
	 * Creates a new instance given a matrix span.
	 * 
	 * @param span  a matrix span
	 * @return  a linearizable object
	 * 
	 * 
	 * @see Matrix
	 */
	public abstract Linearizable instance(Matrix span);
	
	/**
	 * Returns the span of the {@code Linearizable}.
	 * 
	 * @return  a matrix span
	 * 
	 * 
	 * @see Matrix
	 */
	public abstract Matrix Span();
}