package waffles.utils.algebra.utilities;

import waffles.utils.algebra.elements.linear.matrix.Matrix;
import waffles.utils.algebra.elements.linear.vector.Vector;

/**
 * The {@code Generated} interface defines an object generated by a set of vectors.
 *
 * @author Waffles
 * @since 04 Nov 2023
 * @version 1.1
 */
@FunctionalInterface
public interface Generated
{
	/**
	 * Returns the matrix generator of the {@code Generated}.
	 * 
	 * @return  a generating matrix
	 * 
	 * 
	 * @see Matrix
	 */
	public abstract <M extends Matrix> M Generator();
	
	/**
	 * Returns a vector generator of the {@code Generated}.
	 * 
	 * @param i  a generator index
	 * @return   a vector generator
	 * 
	 * 
	 * @see Vector
	 */
	public default <V extends Vector> V Generator(int i)
	{
		return (V) Generator().Column(i);
	}

	/**
	 * Returns a generator count of the {@code Generated}.
	 * 
	 * @return  a generator count
	 */
	public default int Generators()
	{
		return Generator().Columns();
	}
	
	/**
	 * Returns the dimension of the {@code Generated}.
	 * 
	 * @return  a surrounding dimension
	 */
	public default int Dimension()
	{
		return Generator().Rows();
	}
}